### ISSUE TITLE
Adding a SprintSpeed option

### ISSUE THREAD

**Issue by seth-js** [Ch4nKyy/BG3WASD#12]
Would it be possible to add a `SprintSpeed` option under the `Movement` section in the `.toml` config file?

I'm on my second playthrough and jogging around everywhere is getting a bit tedious. The only option I've had is running a speedhack through a trainer, but that cuts dialogue lines short, so I have to enable and disable it a lot.

**Comment by Ch4nKyy** [comment]
I didn't find a way yet to increase the movespeed.

For me it does not have high prio. Maybe someone else figures it out.

**Comment by seth-js** [comment]
>Maybe someone else figures it out.

I hope so. Thanks for the fast reply.

**Comment by DagothUrTheFalse** [comment]
> I didn't find a way yet to increase the movespeed.


You can make the player sprint by using Ctrl+Click as the character will sprint with their weapon drawn, might be able to make the character always do that?

**Comment by seth-js** [comment]
I was able to use [this](https://www.nexusmods.com/baldursgate3/mods/2861?tab=description) in late November. Not sure how well it works now.
