### ISSUE TITLE
Mod not supported in newest BG version Hotfix #18

### ISSUE THREAD

**Issue by FandrewDavid** [Ch4nKyy/BG3WASD#43]
The recent hotfix for Baldur’s Gate 3 made the mod stop working again :(
could we get another update please?

**Comment by Ch4nKyy** [comment]
When I find the time...
But to be honest, Ersh, Norbyte and me are not really motivated to support Hotfix 18. Supposedly, it was only a teeny tiny fix for trading, but they messed up the entire binary file.
I'm pretty sure they built the file with the wrong compiler settings. This happened once before. This causes a lot of work on the modders end, for nothing.
I recommend you to roll back your game version for now. This should be possible on both GOG and Steam.

**Comment by FandrewDavid** [comment]
Oh! That must stink... :(
I'll end up rolling back the game then, thank you anyway for letting me know! :)

**Comment by Ch4nKyy** [comment]
Late reply. Hotfix 19 fixed the issue.
