### ISSUE TITLE
where to download Part-1-NativeModLoader?

### ISSUE THREAD

**Issue by Seigil** [Ch4nKyy/BG3WASD#7]

**Comment by Seigil** [comment]
when i press the "this Mod" link the mod is nowhere to be found.. the link redirected to a release page

**Comment by Seigil** [comment]
https://www.nexusmods.com/baldursgate3/mods/668?tab=files&file_id=5835 
 nvm i found it 
thanks for the great mods btw

**Comment by Ch4nKyy** [comment]
Wow stupid me. I fixed the link. Thanks for reporting!
