### ISSUE TITLE
Feature request: A way to rotate the camera to the movement direction of the character would be amazing.

### ISSUE THREAD

**Issue by xxTheGoDxx** [Ch4nKyy/BG3WASD#8]

**Comment by Ch4nKyy** [comment]
Hi,

In the Accessibility settings of the game, there is Auto-Rotate Camera. I think this is exactly what you want.

Someone said that this was rotating too slowly. Then I hacked it and made it way faster, but then it basically felt like "Rotate Camera Left/Right", but in a wonky way. So I suggest you just bind Rotate Camera Left/Right to A and D.
If it then rotates too slowly, let me know, I should be able to increase this speed.
